<h1> Logistic Regression </h1>


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Lets import sklearn-modules for logistic regression/ Kneighbor classifier/svm

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

import sklearn.datasets as DS     ## We shall use a dataset given to us by sklearn :) 


Import Iris Data set

In [5]:
iris_dataset = DS.load_iris()
iris_dataset.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [17]:
print(iris_dataset.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [6]:
iris_dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
X = iris_dataset.data

In [8]:
y = iris_dataset.target

Lets set up <b> cross-validation </b>

In [9]:
from sklearn.model_selection import cross_val_score

set up Logistic Regressor object and fit the data

In [19]:
logreg = LogisticRegression()
cv_result = cross_val_score(logreg,X,y,cv=5)
np.mean(cv_result)

0.9600000000000002

<h3>Lets do this in train test split and check the results </h3>

In [11]:
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size = 0.3, random_state=42)
newlogreg = LogisticRegression()   # Declare new logistic Regression object
newlogreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

Predict on the test set inputs and compare them with the test set labels

In [13]:
y_pred = newlogreg.predict(X_test)

#Printing out the class names
for i in range(len(iris_dataset.target_names)):
    print("Class {} = {}".format(i,iris_dataset.target_names[i]))
    
#printing out confusion matrix
print("\n\n",confusion_matrix(y_test,y_pred))

Class 0 = setosa
Class 1 = versicolor
Class 2 = virginica


 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [14]:
newlogreg.score(X_test,y_test)

0.9777777777777777

<h3>Better!!! </h3>

In [16]:
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        19
          1       1.00      0.92      0.96        13
          2       0.93      1.00      0.96        13

avg / total       0.98      0.98      0.98        45

